org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true

# Utiliser Java 21 (chemin avec doubles antislashs obligatoires sous Windows)
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.12.8-hotspot
org.gradle.toolchain.auto-detect=false

# Signature release
RELEASE_STORE_FILE=sgrh.keystore
RELEASE_STORE_PASSWORD=20JONAO26
RELEASE_KEY_ALIAS=sgrh
RELEASE_KEY_PASSWORD=20JONAO26